# =================================================================
#                      CakeNear by CakeStudio
#                    https://dsc.gg/cakestudio
# =================================================================

#Настройка стрелок направления
arrows:
  #Спереди от игрока
  N: ⬆
  #Спереди и слева от игрока
  NW: ⬉
  #Слева от игрока
  W: ⬅
  #Сзади и слева от игрока
  SW: ⬋
  #Сзади от игрока
  S: ⬇
  #Сзади и справа от игрока
  SE: ⬊
  #Справа от игрока
  E: ➡
  #Спереди и справа от игрока
  NE: ⬈

#Настройка для команды /near
options:
  #Показывать ли игроков с эффектом невидимости?
  show-invisible-players: false
  #Показывать ли игроков в режиме наблюдателя?
  show-spectators: false

#Настройка дистанций для групп
near-distance:
  #Дистанция по умолчанию, если для группы игрока не найдено других настроек
  default: 100
  #Настройка для конкретных групп
  groups:
    default: 200
    vip: 500
    admin: 1000

#Настройка кулдаунов для команд (в секундах)
command-cooldown:
  #Кулдаун по умолчанию, если для группы игрока не найдено других настроек
  default: 60
  #Настройка для конкретных групп
  groups:
    default: 60
    vip: 30
    admin: 10

#Настройка сообщений
messages:
  #Сообщение, если команду пытается выполнить консоль.
  only-player: "&#C102FA[✘] &fЭту команду может использовать только игрок!"

  #Сообщение, если нет прав на команду /near
  no-permission: "&#C102FA[✘] &7| &fУ вас нет прав!"

  #Сообщение, когда в заданном радиусе нет других игроков.
  no-players-near: "&#C102FA[✘] &7| &fРядом с вами нет игроков!"

  # {time} - оставшееся время в секундах.
  cooldown-message: "&#C102FA[✘] &7| &fВы сможете использовать команду снова через &#C102FA{time} &fсек."

  #Заголовок, который отправляется перед списком игроков.
  player-near: "&#C102FA[🏹] &fИгроки поблизости:"

  # {player} - Никнейм найденного игрока.
  # {distance} - Расстояние до игрока в блоках.
  # {arrows} - Стрелка направления из секции 'arrows'.
  player-near-format: " &f- &7| &#C102FA{player} &f{distance}м. - &7[&#C102FA{arrows}&7]"

  #Команда, которая будет выполняться при нажатии на ник игрока.
  inventory-button-click-command: "/invsee {player}"

  # Право, необходимое для выполнения команды выше.
  # Если оставить пустым (""), проверка проводиться не будет.
  # Пример для EssentialsX: "essentials.invsee"
  inventory-button-permission: "essentials.invsee"

  #Текст, который будет отображаться при наведении курсора на ник игрока (Если есть право).
  inventory-button-hover-text: "&#C102FA[🛡] &fНажмите, чтобы посмотреть инвентарь"

  #Текст при наведении, если у игрока нет права, указанного в 'inventory-button-permission'.
  inventory-button-hover-text-no-permission: "&#C102FA[✘] &fУ вас нет прав на просмотр инвентаря"