# =================================================================
#                      CakeNear by CakeStudio
#                    https://dsc.gg/cakestudio
# =================================================================

#Настройка стрелок направления
arrows:
  #Спереди от игрока
  N: ↑
  #Спереди и слева от игрока
  NW: ↖
  #Слева от игрока
  W: ←
  #Сзади и слева от игрока
  SW: ↙
  #Сзади от игрока
  S: ↓
  #Сзади и справа от игрока
  SE: ↘
  #Справа от игрока
  E: →
  #Спереди и справа от игрока
  NE: ↗

#Настройка дистанций для групп
near-distance:
  #Дистанция по умолчанию, если для группы игрока не найдено других настроек
  default: 100
  #Настройка для конкретных групп
  groups:
    default: 200
    vip: 500
    admin: 1000

#Настройка сообщений
messages:
  #Сообщение, если команду пытается выполнить консоль.
  only-player: "&#C102FA[✘] &fЭту команду может использовать только игрок!"

  #Сообщение, если нет прав на команду /near
  no-permission: "&#C102FA[✘] &fУ вас нет прав!"

  #Сообщение, когда в заданном радиусе нет других игроков.
  no-players-near: "&#C102FA[✘] &7| &fРядом с вами нет игроков!"

  #Заголовок, который отправляется перед списком игроков.
  player-near: "&#C102FA[🏹] &fИгроки поблизости:"

  # {player} - Никнейм найденного игрока.
  # {distance} - Расстояние до игрока в блоках.
  # {arrows} - Стрелка направления из секции 'arrows'.
  player-near-format: " &f- &7| &#C102FA{player} &f{distance}м. - &7[&#C102FA{arrows}&7]"

  #Команда, которая будет выполняться при нажатии на ник игрока.
  inventory-button-click-command: "/invsee {player}"

  #Текст, который будет отображаться при наведении курсора на ник игрока.
  inventory-button-hover-text: "&#C102FA[🛡] &fНажмите, чтобы посмотреть инвентарь"